"""
Author:     Chris Knowles
Date:       Oct 2020
Copyright:  University of Sunderland, (c) 2020
File:       consts.py
Version:    1.0.0
Notes:      Digital version of the 'Deep Space D6' PnP board game from Tau Leader Games
            URL - https://www.tauleadergames.com/deep-space-d6/
                - Constants
"""

# imports
import os


DEBUG = True

COMPANY_NAME = "UoS"
GAME_NAME = "Deep Space D6"
VERSION = "1.0"
WINDOW_CAPTION = "   {0} - ver {1}".format(GAME_NAME, VERSION)
WINDOW_COLOUR_R = 128
WINDOW_COLOUR_G = 0
WINDOW_COLOUR_B = 0

# Default values used when there is no proper configuration information for the various variable game app settings
DEFAULT_DISPLAY_ID = 0
DEFAULT_DISPLAY_WIDTH = 1600
DEFAULT_DISPLAY_HEIGHT = 900
DEFAULT_VSYNC = True
DEFAULT_FULLSCREEN = False

COMPANY_DIR_NAME = (COMPANY_NAME + os.path.sep).replace(os.path.sep, "/")
GAME_NAME_DIR_NAME = (GAME_NAME + os.path.sep).replace(os.path.sep, "/")
USER_SETTINGS_DIR_NAME = ("Settings" + os.path.sep).replace(os.path.sep, "/")
DEFAULT_SETTINGS_FILENAME = "default_settings.ini"
SETTINGS_FILENAME = "settings.ini"

# This path has its root as the game app directory (rather than the operating system user application directory) and is
# used during development only
USER_SETTINGS_PATH = (COMPANY_DIR_NAME + GAME_NAME_DIR_NAME + USER_SETTINGS_DIR_NAME).replace(os.path.sep, "/")

ASSETS_PATH = "assets".replace(os.path.sep, "/")
IMAGES_PATH = ("images" + os.path.sep).replace(os.path.sep, "/")
AUDIO_PATH = ("audio" + os.path.sep).replace(os.path.sep, "/")
DATA_PATH = ("data" + os.path.sep).replace(os.path.sep, "/")

# Common assets, for btn images (D/d:disabled, E/e:enabled, H/h:hover, P/p:pressed)
BACK_SCREEN_IMAGE_FILENAME = "back_screen.png"
BACK_SCREEN_IMAGE_PATH = IMAGES_PATH + BACK_SCREEN_IMAGE_FILENAME

BTN_MISSING_IMAGE_FILENAME = "btn_missing.png"
BTN_MISSING_IMAGE_PATH = IMAGES_PATH + BTN_MISSING_IMAGE_FILENAME

BTN_BACK_D_IMAGE_FILENAME = "btn_missing.png"
BTN_BACK_D_IMAGE_PATH = IMAGES_PATH + BTN_BACK_D_IMAGE_FILENAME
BTN_BACK_E_IMAGE_FILENAME = "back_btn_e.png"
BTN_BACK_E_IMAGE_PATH = IMAGES_PATH + BTN_BACK_E_IMAGE_FILENAME
BTN_BACK_H_IMAGE_FILENAME = "back_btn_h.png"
BTN_BACK_H_IMAGE_PATH = IMAGES_PATH + BTN_BACK_H_IMAGE_FILENAME
BTN_BACK_P_IMAGE_FILENAME = "back_btn_p.png"
BTN_BACK_P_IMAGE_PATH = IMAGES_PATH + BTN_BACK_P_IMAGE_FILENAME

BTN_START_D_IMAGE_FILENAME = "btn_missing.png"
BTN_START_D_IMAGE_PATH = IMAGES_PATH + BTN_START_D_IMAGE_FILENAME
BTN_START_E_IMAGE_FILENAME = "start_btn_e.png"
BTN_START_E_IMAGE_PATH = IMAGES_PATH + BTN_START_E_IMAGE_FILENAME
BTN_START_H_IMAGE_FILENAME = "start_btn_h.png"
BTN_START_H_IMAGE_PATH = IMAGES_PATH + BTN_START_H_IMAGE_FILENAME
BTN_START_P_IMAGE_FILENAME = "start_btn_p.png"
BTN_START_P_IMAGE_PATH = IMAGES_PATH + BTN_START_P_IMAGE_FILENAME

BTN_CONFIRM_D_IMAGE_FILENAME = "btn_missing.png"
BTN_CONFIRM_D_IMAGE_PATH = IMAGES_PATH + BTN_CONFIRM_D_IMAGE_FILENAME
BTN_CONFIRM_E_IMAGE_FILENAME = "confirm_btn_e.png"
BTN_CONFIRM_E_IMAGE_PATH = IMAGES_PATH + BTN_CONFIRM_E_IMAGE_FILENAME
BTN_CONFIRM_H_IMAGE_FILENAME = "confirm_btn_h.png"
BTN_CONFIRM_H_IMAGE_PATH = IMAGES_PATH + BTN_CONFIRM_H_IMAGE_FILENAME
BTN_CONFIRM_P_IMAGE_FILENAME = "confirm_btn_p.png"
BTN_CONFIRM_P_IMAGE_PATH = IMAGES_PATH + BTN_CONFIRM_P_IMAGE_FILENAME

# Splash screen game state assets
SPLASH_SCREEN_IMAGE_FILENAME = "splash_screen.png"
SPLASH_SCREEN_IMAGE_PATH = IMAGES_PATH + SPLASH_SCREEN_IMAGE_FILENAME

# Main menu game state assets, for btn images (D/d:disabled, E/e:enabled, H/h:hover, P/p:pressed)
MAIN_MENU_IMAGE_FILENAME = "main_menu.png"
MAIN_MENU_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_IMAGE_FILENAME

MAIN_MENU_BTN_NEW_D_IMAGE_FILENAME = "btn_missing.png"
MAIN_MENU_BTN_NEW_D_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_NEW_D_IMAGE_FILENAME
MAIN_MENU_BTN_NEW_E_IMAGE_FILENAME = "main_menu_btn_new_e.png"
MAIN_MENU_BTN_NEW_E_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_NEW_E_IMAGE_FILENAME
MAIN_MENU_BTN_NEW_H_IMAGE_FILENAME = "main_menu_btn_new_h.png"
MAIN_MENU_BTN_NEW_H_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_NEW_H_IMAGE_FILENAME
MAIN_MENU_BTN_NEW_P_IMAGE_FILENAME = "main_menu_btn_new_p.png"
MAIN_MENU_BTN_NEW_P_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_NEW_P_IMAGE_FILENAME

MAIN_MENU_BTN_LOAD_D_IMAGE_FILENAME = "btn_missing.png"
MAIN_MENU_BTN_LOAD_D_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_LOAD_D_IMAGE_FILENAME
MAIN_MENU_BTN_LOAD_E_IMAGE_FILENAME = "main_menu_btn_load_e.png"
MAIN_MENU_BTN_LOAD_E_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_LOAD_E_IMAGE_FILENAME
MAIN_MENU_BTN_LOAD_H_IMAGE_FILENAME = "main_menu_btn_load_h.png"
MAIN_MENU_BTN_LOAD_H_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_LOAD_H_IMAGE_FILENAME
MAIN_MENU_BTN_LOAD_P_IMAGE_FILENAME = "main_menu_btn_load_p.png"
MAIN_MENU_BTN_LOAD_P_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_LOAD_P_IMAGE_FILENAME

MAIN_MENU_BTN_OPTIONS_D_IMAGE_FILENAME = "btn_missing.png"
MAIN_MENU_BTN_OPTIONS_D_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_OPTIONS_D_IMAGE_FILENAME
MAIN_MENU_BTN_OPTIONS_E_IMAGE_FILENAME = "main_menu_btn_options_e.png"
MAIN_MENU_BTN_OPTIONS_E_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_OPTIONS_E_IMAGE_FILENAME
MAIN_MENU_BTN_OPTIONS_H_IMAGE_FILENAME = "main_menu_btn_options_h.png"
MAIN_MENU_BTN_OPTIONS_H_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_OPTIONS_H_IMAGE_FILENAME
MAIN_MENU_BTN_OPTIONS_P_IMAGE_FILENAME = "main_menu_btn_options_p.png"
MAIN_MENU_BTN_OPTIONS_P_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_OPTIONS_P_IMAGE_FILENAME

MAIN_MENU_BTN_CREDITS_D_IMAGE_FILENAME = "btn_missing.png"
MAIN_MENU_BTN_CREDITS_D_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_CREDITS_D_IMAGE_FILENAME
MAIN_MENU_BTN_CREDITS_E_IMAGE_FILENAME = "main_menu_btn_credits_e.png"
MAIN_MENU_BTN_CREDITS_E_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_CREDITS_E_IMAGE_FILENAME
MAIN_MENU_BTN_CREDITS_H_IMAGE_FILENAME = "main_menu_btn_credits_h.png"
MAIN_MENU_BTN_CREDITS_H_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_CREDITS_H_IMAGE_FILENAME
MAIN_MENU_BTN_CREDITS_P_IMAGE_FILENAME = "main_menu_btn_credits_p.png"
MAIN_MENU_BTN_CREDITS_P_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_CREDITS_P_IMAGE_FILENAME

MAIN_MENU_BTN_EXTRAS_D_IMAGE_FILENAME = "btn_missing.png"
MAIN_MENU_BTN_EXTRAS_D_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_EXTRAS_D_IMAGE_FILENAME
MAIN_MENU_BTN_EXTRAS_E_IMAGE_FILENAME = "main_menu_btn_extras_e.png"
MAIN_MENU_BTN_EXTRAS_E_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_EXTRAS_E_IMAGE_FILENAME
MAIN_MENU_BTN_EXTRAS_H_IMAGE_FILENAME = "main_menu_btn_extras_h.png"
MAIN_MENU_BTN_EXTRAS_H_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_EXTRAS_H_IMAGE_FILENAME
MAIN_MENU_BTN_EXTRAS_P_IMAGE_FILENAME = "main_menu_btn_extras_p.png"
MAIN_MENU_BTN_EXTRAS_P_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_EXTRAS_P_IMAGE_FILENAME

MAIN_MENU_BTN_QUIT_D_IMAGE_FILENAME = "btn_missing.png"
MAIN_MENU_BTN_QUIT_D_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_QUIT_D_IMAGE_FILENAME
MAIN_MENU_BTN_QUIT_E_IMAGE_FILENAME = "main_menu_btn_quit_e.png"
MAIN_MENU_BTN_QUIT_E_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_QUIT_E_IMAGE_FILENAME
MAIN_MENU_BTN_QUIT_H_IMAGE_FILENAME = "main_menu_btn_quit_h.png"
MAIN_MENU_BTN_QUIT_H_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_QUIT_H_IMAGE_FILENAME
MAIN_MENU_BTN_QUIT_P_IMAGE_FILENAME = "main_menu_btn_quit_p.png"
MAIN_MENU_BTN_QUIT_P_IMAGE_PATH = IMAGES_PATH + MAIN_MENU_BTN_QUIT_P_IMAGE_FILENAME

# New game screen game state assets, for btn images (D/d:disabled, E/e:enabled, H/h:hover, P/p:pressed)
NEW_GAME_SCREEN_IMAGE_FILENAME = "back_screen.png"
NEW_GAME_SCREEN_IMAGE_PATH = IMAGES_PATH + NEW_GAME_SCREEN_IMAGE_FILENAME

# Load game screen game state assets, for btn images (D/d:disabled, E/e:enabled, H/h:hover, P/p:pressed)
LOAD_GAME_SCREEN_IMAGE_FILENAME = "back_screen.png"
LOAD_GAME_SCREEN_IMAGE_PATH = IMAGES_PATH + LOAD_GAME_SCREEN_IMAGE_FILENAME

# Options screen game state assets, for btn images (D/d:disabled, E/e:enabled, H/h:hover, P/p:pressed)
OPTIONS_SCREEN_IMAGE_FILENAME = "back_screen.png"
OPTIONS_SCREEN_IMAGE_PATH = IMAGES_PATH + OPTIONS_SCREEN_IMAGE_FILENAME

# Credits screen game state assets, for btn images (D/d:disabled, E/e:enabled, H/h:hover, P/p:pressed)
CREDITS_SCREEN_IMAGE_FILENAME = "back_screen.png"
CREDITS_SCREEN_IMAGE_PATH = IMAGES_PATH + CREDITS_SCREEN_IMAGE_FILENAME

# Extras screen game state assets, for btn images (D/d:disabled, E/e:enabled, H/h:hover, P/p:pressed)
EXTRAS_SCREEN_IMAGE_FILENAME = "back_screen.png"
EXTRAS_SCREEN_IMAGE_PATH = IMAGES_PATH + EXTRAS_SCREEN_IMAGE_FILENAME

# Quit screen game state assets, for btn images (D/d:disabled, E/e:enabled, H/h:hover, P/p:pressed)
QUIT_SCREEN_IMAGE_FILENAME = "back_screen.png"
QUIT_SCREEN_IMAGE_PATH = IMAGES_PATH + QUIT_SCREEN_IMAGE_FILENAME

# Game play screen game state assets, for btn images (D/d:disabled, E/e:enabled, H/h:hover, P/p:pressed)
GAME_PLAY_SCREEN_IMAGE_FILENAME = "back_screen.png"
GAME_PLAY_SCREEN_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_SCREEN_IMAGE_FILENAME

# Game play menu screen game state assets, for btn images (D/d:disabled, E/e:enabled, H/h:hover, P/p:pressed)
GAME_PLAY_MENU_SCREEN_IMAGE_FILENAME = "game_play_menu_screen.png"
GAME_PLAY_MENU_SCREEN_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_SCREEN_IMAGE_FILENAME
GAME_PLAY_MENU_MASK_IMAGE_FILENAME = "game_play_menu_mask.png"
GAME_PLAY_MENU_MASK_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_MASK_IMAGE_FILENAME

GAME_PLAY_MENU_BTN_RESUME_D_IMAGE_FILENAME = "btn_missing.png"
GAME_PLAY_MENU_BTN_RESUME_D_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_RESUME_D_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_RESUME_E_IMAGE_FILENAME = "game_play_menu_btn_resume_e.png"
GAME_PLAY_MENU_BTN_RESUME_E_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_RESUME_E_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_RESUME_H_IMAGE_FILENAME = "game_play_menu_btn_resume_h.png"
GAME_PLAY_MENU_BTN_RESUME_H_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_RESUME_H_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_RESUME_P_IMAGE_FILENAME = "game_play_menu_btn_resume_p.png"
GAME_PLAY_MENU_BTN_RESUME_P_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_RESUME_P_IMAGE_FILENAME

GAME_PLAY_MENU_BTN_SAVE_D_IMAGE_FILENAME = "btn_missing.png"
GAME_PLAY_MENU_BTN_SAVE_D_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_SAVE_D_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_SAVE_E_IMAGE_FILENAME = "game_play_menu_btn_save_e.png"
GAME_PLAY_MENU_BTN_SAVE_E_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_SAVE_E_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_SAVE_H_IMAGE_FILENAME = "game_play_menu_btn_save_h.png"
GAME_PLAY_MENU_BTN_SAVE_H_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_SAVE_H_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_SAVE_P_IMAGE_FILENAME = "game_play_menu_btn_save_p.png"
GAME_PLAY_MENU_BTN_SAVE_P_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_SAVE_P_IMAGE_FILENAME

GAME_PLAY_MENU_BTN_LOAD_D_IMAGE_FILENAME = "btn_missing.png"
GAME_PLAY_MENU_BTN_LOAD_D_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_LOAD_D_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_LOAD_E_IMAGE_FILENAME = "game_play_menu_btn_load_e.png"
GAME_PLAY_MENU_BTN_LOAD_E_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_LOAD_E_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_LOAD_H_IMAGE_FILENAME = "game_play_menu_btn_load_h.png"
GAME_PLAY_MENU_BTN_LOAD_H_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_LOAD_H_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_LOAD_P_IMAGE_FILENAME = "game_play_menu_btn_load_p.png"
GAME_PLAY_MENU_BTN_LOAD_P_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_LOAD_P_IMAGE_FILENAME

GAME_PLAY_MENU_BTN_OPTIONS_D_IMAGE_FILENAME = "btn_missing.png"
GAME_PLAY_MENU_BTN_OPTIONS_D_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_OPTIONS_D_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_OPTIONS_E_IMAGE_FILENAME = "game_play_menu_btn_options_e.png"
GAME_PLAY_MENU_BTN_OPTIONS_E_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_OPTIONS_E_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_OPTIONS_H_IMAGE_FILENAME = "game_play_menu_btn_options_h.png"
GAME_PLAY_MENU_BTN_OPTIONS_H_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_OPTIONS_H_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_OPTIONS_P_IMAGE_FILENAME = "game_play_menu_btn_options_p.png"
GAME_PLAY_MENU_BTN_OPTIONS_P_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_OPTIONS_P_IMAGE_FILENAME

GAME_PLAY_MENU_BTN_MAIN_D_IMAGE_FILENAME = "btn_missing.png"
GAME_PLAY_MENU_BTN_MAIN_D_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_MAIN_D_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_MAIN_E_IMAGE_FILENAME = "game_play_menu_btn_main_e.png"
GAME_PLAY_MENU_BTN_MAIN_E_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_MAIN_E_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_MAIN_H_IMAGE_FILENAME = "game_play_menu_btn_main_h.png"
GAME_PLAY_MENU_BTN_MAIN_H_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_MAIN_H_IMAGE_FILENAME
GAME_PLAY_MENU_BTN_MAIN_P_IMAGE_FILENAME = "game_play_menu_btn_main_p.png"
GAME_PLAY_MENU_BTN_MAIN_P_IMAGE_PATH = IMAGES_PATH + GAME_PLAY_MENU_BTN_MAIN_P_IMAGE_FILENAME

# Save game screen game state assets, for btn images (D/d:disabled, E/e:enabled, H/h:hover, P/p:pressed)
SAVE_GAME_SCREEN_IMAGE_FILENAME = "back_screen.png"
SAVE_GAME_SCREEN_IMAGE_PATH = IMAGES_PATH + SAVE_GAME_SCREEN_IMAGE_FILENAME

# Game board game object assets
GAME_MAIN_BOARD_IMAGE_FILENAME = "game_main_board.png"
GAME_MAIN_BOARD_IMAGE_PATH = IMAGES_PATH + GAME_MAIN_BOARD_IMAGE_FILENAME

# Game data model object assets
DATA_PATH_FULL = (ASSETS_PATH + os.path.sep).replace(os.path.sep, "/") + DATA_PATH
GAME_THREAT_CARDS_DATA_FILENAME = "threat_cards.json"
GAME_THREAT_CARDS_DATA_PATH = DATA_PATH_FULL + GAME_THREAT_CARDS_DATA_FILENAME

GAME_SHIP_DATA_HALCYON_FILENAME = "halcyon.json"
GAME_SHIP_DATA_HALCYON_PATH = DATA_PATH_FULL + GAME_SHIP_DATA_HALCYON_FILENAME
